const assert=require('assert/strict'),{detect,forward,classify}=require('./price-detector.cjs');let count=0;const test=(n,f)=>{f();count++;console.log('PASS '+n);};
const b=(m,c=100,d='2026-09-16')=>({stock_id:'3450',trade_date:d,timestamp:d+'T09:'+String(m).padStart(2,'0')+':00+08:00',open:c,high:c,low:c,close:c,complete:true,is_synthetic:false});
const history=Array.from({length:10},(_,i)=>{const d='2026-09-'+String(i+1).padStart(2,'0');return [b(0,100,d),b(1,i%2?99:101,d)];}).flat();
const go=(current,h=history,as_of='2026-09-16T14:00:00+08:00')=>detect({stock_id:'3450',trade_date:'2026-09-16',current,history:h,as_of,previous_close:80});
test('volume absent does not gate price',()=>assert.equal(go([b(0),b(1,105)]).events[0].primary_price_spike_ratio,5));
test('abs includes down returns',()=>assert.equal(go([b(0),b(1,105)]).rows[1].same_minute_baseline,1));
test('opening gap percent and excluded',()=>{const r=go([b(0)]).rows[0];assert.equal(r.open_gap_return,25);assert.equal(r.primary_price_spike_ratio,null);assert.equal(r.price_up_anomaly_event,false);});
test('flat and negative never ratio or event',()=>{for(const p of [99,100]){const r=go([b(0),b(1,p)]).rows[1];assert.equal(r.primary_price_spike_ratio,null);assert.equal(r.price_up_anomaly_event,false);assert.equal(r.signal_level,'NORMAL');}});
test('historical minimum ten',()=>assert.equal(go([b(0),b(1,105)],history.slice(2)).rows[1].primary_price_spike_ratio,null));
test('zero median blocks',()=>{const r=go([b(0),b(1,105)],history.map(x=>({...x,open:100,high:100,low:100,close:100}))).rows[1];assert.equal(r.baseline_zero,true);assert.equal(r.primary_price_spike_ratio,null);});
test('no cross day or missing minute returns',()=>assert.equal(go([b(0),b(2,110)]).rows[1].return_1m,null));
test('synthetic cannot supply previous close',()=>assert.equal(go([{...b(0),is_synthetic:true},b(1,105)]).rows[1].primary_price_spike_ratio,null));
test('completed boundary',()=>assert.equal(go([b(0),b(1,105)],history,'2026-09-16T09:01:59+08:00').events.length,0));
test('twenty returns need twentyone prior closes',()=>{const a=Array.from({length:22},(_,i)=>b(i,100+i));assert.equal(go(a).rows[21].rolling20_sample_count,20);assert.equal(go(a).rows[21].primary_baseline_method,'ROLLING_20M_MEDIAN');});
test('current cannot contaminate baseline',()=>{const a=Array.from({length:22},(_,i)=>b(i,100+i)),before=go(a).rows[21].rolling20_baseline;a[21]=b(21,1000);assert.equal(go(a).rows[21].rolling20_baseline,before);});
test('future cannot change prior signal',()=>{const a=[b(0),b(1,105)],before=go(a).rows[1];a.push(b(2,1000));assert.deepEqual(go(a).rows[1],before);});
test('new level names and thresholds',()=>assert.deepEqual([2,3,5,8].map(classify),['PRICE_ACCELERATION_UP','STRONG_PRICE_ACCELERATION_UP','PRICE_SPIKE_UP','EXTREME_PRICE_SPIKE_UP']));
test('no minimum actual return filter',()=>{const h=history.map(x=>({...x,open:x.close===100?100:100.01,high:x.close===100?100:100.01,low:x.close===100?100:100.01,close:x.close===100?100:100.01}));assert.equal(go([b(0),b(1,100.05)],h).events.length,1);});
test('forward is separate and future not yet available null',()=>{const a=[b(0),b(1,105),b(2,106)],e=go(a).events;assert.equal(Object.hasOwn(e[0],'forward_return_1m'),false);assert.equal(forward(e,a,'2026-09-16T09:02:59+08:00')[0].forward_return_1m,null);});
test('duplicates rejected',()=>assert.throws(()=>go([b(0),b(0)])));
console.log(JSON.stringify({tests:count,passed:count}));
