const assert=require('assert/strict'),{detect,forward}=require('./volume-detector.cjs');let count=0;
const bar=(time,vol=10,day='2026-09-16')=>({trade_date:day,stock_id:'3450',timestamp:day+'T'+time+':00+08:00',open:100,high:100,low:100,close:100,volume_raw:vol,volume_raw_unit:'LOTS',complete:true,is_synthetic:false});
const hist=Array.from({length:10},(_,i)=>bar('09:00',10,`2026-09-${String(i+1).padStart(2,'0')}`));
const go=(current,history=hist,as_of='2026-09-16T14:00:00+08:00')=>detect({stock_id:'3450',trade_date:'2026-09-16',current,history,as_of});
const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
test('optional turnover null does not block event',()=>{const r=go([bar('09:00',50)]).rows[0];assert.equal(r.primary_ratio,5);assert.equal(r.turnover_value_1m,null);assert.equal(r.data_gap,false);});
test('canonical shares and lots',()=>{const r=go([bar('09:00',50)]).rows[0];assert.equal(r.volume_shares,50000);assert.equal(r.same_minute_baseline,10000);assert.equal(r.volume_lots,50);});
test('shares never double multiplied',()=>assert.equal(go([{...bar('09:00',50000),volume_raw_unit:'SHARES'}]).rows[0].primary_ratio,5));
test('unknown unit remains a gap row',()=>{const r=go([{...bar('09:00'),volume_raw_unit:'?'}]);assert.equal(r.rows.length,1);assert.equal(r.rows[0].data_gap,true);assert.equal(r.events.length,0);});
test('synthetic incomplete and wrong date rejected',()=>{for(const changes of [{is_synthetic:true},{complete:false},{trade_date:'2026-09-15'}]){const r=go([{...bar('09:00',100),...changes}]).rows[0];assert.equal(r.data_gap,true);assert.equal(r.primary_ratio,null);}});
test('less than ten historical days has no ratio',()=>assert.equal(go([bar('09:00',50)],hist.slice(0,9)).rows[0].primary_ratio,null));
test('zero denominator no epsilon',()=>{const r=go([bar('09:00',50)],hist.map(x=>({...x,volume_raw:0}))).rows[0];assert.equal(r.baseline_zero,true);assert.equal(r.primary_ratio,null);});
test('current excluded from rolling',()=>{const a=Array.from({length:22},(_,i)=>bar('09:'+String(i).padStart(2,'0'),i===21?100:10));assert.equal(go(a).rows.at(-1).primary_ratio,10);});
test('rolling needs twenty completed bars',()=>{const r=go([bar('09:00'),bar('09:21',100)]).rows[1];assert.equal(r.rolling_insufficient_sample,true);assert.equal(r.primary_ratio,null);});
test('future bars cannot change earlier signal',()=>{const a=Array.from({length:22},(_,i)=>bar('09:'+String(i).padStart(2,'0'))),x=go(a).rows[21];a.push(bar('09:22',100000));assert.deepEqual(go(a).rows[21],x);});
test('as of completion boundary',()=>{assert.equal(go([bar('09:00',50)],hist,'2026-09-16T09:00:59+08:00').events.length,0);assert.equal(go([bar('09:00',50)],hist,'2026-09-16T09:01:00+08:00').events.length,1);});
test('late data unavailable as of rejected',()=>assert.equal(go([{...bar('09:00',50),available_at:'2026-09-16T15:00:00+08:00'}]).events.length,0));
test('duplicate minutes rejected',()=>assert.throws(()=>go([bar('09:00'),bar('09:00')])));
test('all events retained no cooldown in engine',()=>{const a=Array.from({length:23},(_,i)=>bar('09:'+String(i).padStart(2,'0'),i>=21?50:10));assert.equal(go(a).events.filter(e=>e.timestamp.includes('09:2')).length,2);});
test('forward is separate and cannot use not yet complete bar',()=>{const a=[bar('09:00',50),{...bar('09:01'),close:101,high:101}],e=go(a).events;assert.equal(Object.hasOwn(e[0],'forward_return_1m'),false);assert.equal(forward(e,a,'2026-09-16T09:01:59+08:00')[0].forward_return_1m,null);assert.ok(Math.abs(forward(e,a,'2026-09-16T09:02:00+08:00')[0].forward_return_1m-.01)<1e-12);});
test('numeric strings not silently coerced',()=>assert.equal(go([{...bar('09:00'),volume_raw:'50'}]).rows[0].data_gap,true));
console.log(JSON.stringify({tests:count,passed:count}));
