const assert=require('assert/strict'),{evaluate}=require('./outside-detector.cjs');let count=0;const test=(n,f)=>{f();count++;console.log('PASS '+n);};
const b=(minute=30,o=300,i=100,date='2026-09-16')=>({stock_id:'3450',trade_date:date,timestamp:date+'T09:'+String(minute).padStart(2,'0')+':00+08:00',side_volume_timestamp:date+'T09:'+String(minute).padStart(2,'0')+':59+08:00',outside_1m:o,inside_1m:i,volume_unit:'LOTS',complete:true,is_synthetic:false,aggregation:'ONE_MINUTE',classification_source:'ISOLATED_TEST_FIXTURE'});
const rolling=Array.from({length:20},(_,i)=>b(i+10,100,100));const run=(current=b(),rw=rolling,now='2026-09-16T09:31:00+08:00')=>evaluate({current,rolling:rw,processing_timestamp:now});
test('raw versus dynamic independent',()=>{const x=run();assert.equal(x.raw_outside_strength,3);assert.equal(x.primary_dynamic_ratio,3);assert.equal(run(b(),rolling.map(x=>({...x,outside_1m:200}))).primary_dynamic_ratio,1.5);});
test('shares normalized no mixed units',()=>{const x=run({...b(),volume_unit:'SHARES',outside_1m:300000,inside_1m:100000});assert.equal(x.outside_1m,300000);assert.equal(x.primary_dynamic_ratio,3);});
test('outside only no infinity or raw strong',()=>{const x=run(b(30,100,0));assert.equal(x.side_state,'OUTSIDE_ONLY');assert.equal(x.raw_outside_strength,null);assert.equal(x.RAW_OUTSIDE_STRONG,false);});
test('both zero no side event',()=>assert.equal(run(b(30,0,0)).side_state,'NO_VALID_SIDE_VOLUME'));
test('zero denominators excluded counted',()=>{const rw=rolling.map((x,i)=>i<10?{...x,inside_1m:0}:x),x=run(b(),rw);assert.equal(x.rolling_zero_denominator_sample_count,10);assert.equal(x.rolling_valid_ratio_count,10);assert.equal(x.primary_dynamic_ratio,3);});
test('less ten ratios insufficient',()=>assert.equal(run(b(),rolling.map((x,i)=>i<11?{...x,inside_1m:0}:x)).primary_dynamic_ratio,null));
test('zero baseline never epsilon',()=>assert.equal(run(b(),rolling.map(x=>({...x,outside_1m:0}))).baseline_zero,true));
test('neutral unknown remain separate',()=>{const x=run({...b(),neutral_1m:50,unknown_1m:50,total_1m:500});assert.equal(x.raw_outside_strength,3);assert.equal(x.side_coverage_ratio,.8);assert.equal(x.neutral_1m,50000);});
test('stale blocked exact 120 boundary',()=>{assert.equal(run(b(),rolling,'2026-09-16T09:32:59+08:00').data_gap,false);assert.equal(run(b(),rolling,'2026-09-16T09:33:00+08:00').primary_dynamic_ratio,null);});
test('cumulative cannot impersonate minute',()=>assert.equal(run({...b(),aggregation:'CUMULATIVE'}).data_gap,true));
test('unknown units rejected',()=>assert.equal(run({...b(),volume_unit:'?'}).primary_dynamic_ratio,null));
test('future event rejected',()=>assert.equal(run({...b(),side_volume_timestamp:'2026-09-16T09:32:00+08:00'}).data_gap,true));
test('low volume retained',()=>assert.equal(run(b(30,.03,.01)).raw_outside_strength,3));
test('separate events at two',()=>{assert.deepEqual(run().event_types,['RAW_OUTSIDE_STRENGTH_EVENT','DYNAMIC_OUTSIDE_STRENGTH_EVENT']);assert.equal(run(b(30,200,100)).dynamic_event,true);});
test('same minute historical minimum and median',()=>{const h=Array.from({length:10},(_,i)=>b(5,120,100,'2026-09-'+String(i+1).padStart(2,'0')));const x=evaluate({current:b(5),history:h,processing_timestamp:'2026-09-16T09:06:00+08:00'});assert.equal(x.primary_dynamic_ratio,2.5);});
test('raw only',()=>{const x=run(b(),rolling.map(x=>({...x,outside_1m:200})));assert.deepEqual(x.event_types,['RAW_OUTSIDE_STRENGTH_EVENT']);});
test('dynamic only',()=>{const x=run(b(30,100,100),rolling.map(x=>({...x,outside_1m:50})));assert.deepEqual(x.event_types,['DYNAMIC_OUTSIDE_STRENGTH_EVENT']);});
test('neither',()=>assert.deepEqual(run(b(30,100,100)).event_types,[]));
test('stale has no events',()=>assert.deepEqual(run(b(),rolling,'2026-09-16T09:33:00+08:00').event_types,[]));
test('ten valid in exact 20 minute window sufficient',()=>assert.equal(run(b(),rolling.slice(10)).primary_dynamic_ratio,3));
test('older rows never backfill exact window',()=>assert.equal(run(b(),rolling.slice(11).concat(b(9))).primary_dynamic_ratio,null));
test('change and acceleration use exact previous minute',()=>{const x=run();assert.equal(x.raw_strength_change,2);assert.equal(x.raw_strength_acceleration,3);assert.equal(run(b(),rolling.slice(0,-1)).raw_strength_change,null);});
test('continuous counters and day boundary',()=>{const prev={stock_id:'3450',trade_date:'2026-09-16',timestamp:b(29).timestamp,raw_event:true,dynamic_event:true,consecutive_raw_strong_minutes:2,consecutive_dynamic_strong_minutes:3};const x=evaluate({current:b(),rolling,processing_timestamp:'2026-09-16T09:31:00+08:00',previous_result:prev});assert.equal(x.consecutive_raw_strong_minutes,3);assert.equal(x.consecutive_dynamic_strong_minutes,4);const y=evaluate({current:b(),rolling,processing_timestamp:'2026-09-16T09:31:00+08:00',previous_result:{...prev,trade_date:'2026-09-15'}});assert.equal(y.consecutive_raw_strong_minutes,1);});
console.log(JSON.stringify({tests:count,passed:count,fixture_only:true,complete:false}));

