'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {mapQuotes,source_hash}=require('./quote-adapter.cjs');
const out=path.resolve(process.argv[2]||path.join(__dirname,'evidence')),tests=[],nowMs=Date.parse('2026-10-06T04:45:00Z'),event='2026-10-06T04:44:59.000Z';
const row=(symbol,extra={})=>({code:symbol,trade_date:'2026-10-06',market:'TSE',close:100,open:99,high:101,low:98,previousClose:99,quoteSource:'fugle-ws-trades',lastTradeTime:event,exchangeTime:event,receivedAt:event,tradeSerial:1,tradeVolume:600,turnoverVolumeEvidence:{value:600,unit:'lots',event_at:event,source:'fugle.websocket.aggregates.total.tradeVolume',is_synthetic:false},...extra});
const options={nowMs,cacheUpdatedAt:event,prioritySymbols:['2330','3163','1101']};
function test(name,fn){try{fn();tests.push({name,status:'PASS'});}catch(e){tests.push({name,status:'FAIL',error:e.stack});}console.log(name+': '+tests.at(-1).status);}
test('exact original quote expression and liquidity bundle known values',()=>{const r=mapQuotes({...options,rawRows:[row('2330')]}).rows[0];assert.equal(r.price,100);assert.equal(r.total_volume,600);assert.equal(r.payload.volume_strategy_usable,true);assert.equal(r.last_trade_time,event);assert.equal(r.quote_seen_at,event);assert.equal(r.trade_value,null);});
test('changed-symbol merge output matches full original mapping subset',()=>{const base=[row('2330'),row('3163')],previous=mapQuotes({...options,rawRows:base}).mergedRows;const next=[row('2330',{close:102,high:103,tradeSerial:2}),base[1]],full=mapQuotes({...options,rawRows:next,previousRows:previous}),inc=mapQuotes({...options,rawRows:next,previousRows:previous,changedSymbols:['2330']});assert.deepEqual(inc.rows,full.rows.filter(r=>r.symbol==='2330'));assert.deepEqual(inc.mergedRows,full.mergedRows);});
test('same-price new serial keeps original freshness and fields',()=>{const a=mapQuotes({...options,rawRows:[row('2330')]}),b=mapQuotes({...options,rawRows:[row('2330',{tradeSerial:2})],previousRows:a.mergedRows,changedSymbols:['2330']});assert.equal(b.rows[0].price,100);assert.equal(b.rows[0].quote_seen_at,event);});
test('old/future/missing trade time remain excluded by unmodified 120s Gate',()=>{for(const lastTradeTime of ['2026-10-06T04:40:00Z','2026-10-06T04:46:00Z',null])assert.equal(mapQuotes({...options,rawRows:[row('2330',{lastTradeTime})]}).rows.length,0);});
test('unknown volume evidence stays unavailable despite raw numeric volume',()=>{const r=mapQuotes({...options,rawRows:[row('2330',{turnoverVolumeEvidence:{}})]}).rows[0];assert.equal(r.total_volume,null);assert.equal(r.payload.volume_strategy_usable,false);});
test('non-priority stock not silently admitted by readthrough adapter',()=>assert.equal(mapQuotes({...options,rawRows:[row('9999')]}).rows.length,0));
test('duplicate raw quote identity rejects',()=>assert.throws(()=>mapQuotes({...options,rawRows:[row('2330'),row('2330')]}),/IDENTITY/));
fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'quote-tests.json'),JSON.stringify({status:tests.every(t=>t.status==='PASS')?'PASS':'FAIL',tests,source_hash,scope:'existing quote merge/readthrough expression + actual liquidity module; DB/checkpoint/time aging unconnected'},null,2));if(tests.some(t=>t.status!=='PASS'))process.exitCode=1;
