'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const I=require('./incremental-writer.cjs'),{sha}=require('../../lib/mother-change-evidence.cjs');
const {recover}=require('../../lib/mother-evidence-recovery.cjs');
const {createParentBridge}=require('../../lib/mother-evidence-parent.cjs'),{createBridge}=require('../../lib/mother-evidence-bridge.cjs');
const {originalCandleStage,sourceHash}=require('./writer-oracle.cjs');
const out=path.resolve(process.argv[2]||path.join(__dirname,'evidence')),scratch=fs.mkdtempSync(path.join(os.tmpdir(),'mp-phase2-'));fs.mkdirSync(out,{recursive:true});
const results=[],limits={maxEvents:1024,maxBytes:4*1048576,maxBatchEvents:128,maxBatchBytes:524288,maxAgeMs:15000,minFreeBytes:1048576,maxDiskBytes:64*1048576};
const tradeDate='2026-10-06',nowMs=Date.parse(tradeDate+'T05:00:00Z'),cacheUpdatedAt=new Date(nowMs).toISOString(),options={tradeDate,nowMs,cacheUpdatedAt,allowedSymbols:new Set(['2330','3163'])};
const row=(symbol='2330',minute=0,volume=10)=>({symbol,market:'TSE',tradeDate,candleTime:new Date(Date.parse(tradeDate+'T01:00:00Z')+minute*60000).toISOString(),candleSeenAt:cacheUpdatedAt,open:100,high:102,low:99,close:101,volume,source:'fugle-ws-candles',sourceChannel:'candles',candleOrigin:'websocket_candle',intradayOddLot:false,restRepairRow:false,synthetic:false,volumeStrategyUsable:true});
const pause=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn){const end=Date.now()+20000;while(!fn()){if(Date.now()>end)throw Error('TEST_TIMEOUT');await pause(5);}}
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});}console.log(name+': '+results.at(-1).status);}
async function fixture(kind,changes){const base=path.join(scratch,crypto.randomUUID()),dir=path.join(base,'feed'),cache=path.join(base,'cache.json');fs.mkdirSync(base);fs.writeFileSync(cache,JSON.stringify({[kind==='candle'?'candles':'quotes']:[]}));const epoch=crypto.randomUUID(),config={dir,epoch,kind,producerVersion:'OFFLINE_TEST',limits};config.recovery=recover({cacheFile:cache,kind,targetEpoch:epoch,targetDir:dir,out:path.join(base,'recovery'),bootstrap:true});const b=kind==='candle'?createParentBridge(config):createBridge(config);try{await until(()=>b.status().ready||b.status().state!=='RUNNING');assert(b.status().ready);let n=0;for(const ch of changes){const token=b.begin(ch);assert(token,b.status().reason);const start=process.hrtime.bigint().toString();fs.writeFileSync(cache,JSON.stringify({[kind==='candle'?'candles':'quotes']:ch.map(x=>x.merged)}));const end=process.hrtime.bigint().toString();b.confirm(token,{ok:true,original_ack:true,cache_file:cache,cache_started_ns:start,cache_finished_ns:end,rows_json:JSON.stringify(ch.map(x=>x.merged))});n++;await until(()=>kind==='candle'?b.status().completed_parents===n:b.status().committed_count>=n);}
 const snapshot=path.join(base,'fixed');fs.cpSync(dir,snapshot,{recursive:true});return {dir:snapshot,kind,epoch,tradeDate,continuityProof:{status:'OFFLINE_FIXED_SEGMENT',epoch,manifest_hash:I.snapshotManifest(snapshot).hash}};
 }finally{await b.stop('OFFLINE_TEST_FINISHED');}}
function cloneFixture(f){const dir=path.join(scratch,crypto.randomUUID());fs.cpSync(f.dir,dir,{recursive:true});return {...f,dir};}
function reseal(f){f.continuityProof={...f.continuityProof,manifest_hash:I.snapshotManifest(f.dir).hash};return f;}
async function main(){const a=row(),b=row('2330',1),old=row('2330',0,20),quality={...old,volumeStrategyUsable:false};const f=await fixture('candle',[[{merged:a},{merged:b}],[{previous:a,merged:old}],[{previous:old,merged:quality}]]);
 await check('actual C2 v3 parent audit and old-minute final revision',()=>{const p=I.readCommittedSegment(f);assert.equal(p.events.length,4);assert.equal(p.changedCandleKeys.length,2);assert.equal(p.rows.find(x=>x.candleTime===a.candleTime).volumeStrategyUsable,false);});
 await check('checkpoint replay yields no events; epoch rollover blocks',()=>{const p=I.readCommittedSegment(f);assert.equal(I.readCommittedSegment({...f,checkpoint:p.next}).events.length,0);assert.throws(()=>I.readCommittedSegment({...f,checkpoint:{...p.next,epoch:'other'}}),/IDENTITY/);});
 await check('forged checkpoint anchor rejected',()=>{const p=I.readCommittedSegment(f);assert.throws(()=>I.readCommittedSegment({...f,checkpoint:{...p.next,commit_hash:'bad'}}),/ANCHOR/);});
 await check('C2 continuous=false cannot authorize feed',()=>assert.throws(()=>I.readCommittedSegment({...f,continuityProof:null}),/CONTINUITY/));
 for(const type of ['commit','parent-complete'])await check('missing '+type+' forces full fallback',()=>{const c=cloneFixture(f),name=fs.readdirSync(c.dir).filter(n=>n.endsWith('.'+type+'.json')).at(-1);fs.unlinkSync(path.join(c.dir,name));reseal(c);const p=I.safeRead(c,()=>({complete:true,kind:'candle',trade_date:tradeDate,rows:[a,b],sha256:sha([a,b])}));assert.equal(p.mode,'FULL_FALLBACK');assert.equal(p.continuity_reestablished,false);});
 await check('tampered payload hash fails and invalid fallback stays BLOCKED',()=>{const c=cloneFixture(f),file=path.join(c.dir,'000000000001.prepare.json'),x=JSON.parse(fs.readFileSync(file));x.events[0].payload.close=999;fs.writeFileSync(file,JSON.stringify(x));reseal(c);assert.equal(I.safeRead(c,()=>({complete:false})).mode,'BLOCKED');});
 await check('date mismatch fails closed',()=>assert.throws(()=>I.readCommittedSegment({...f,tradeDate:'2026-10-07'}),/IDENTITY/));
 await check('bounded event budget fails closed',()=>assert.throws(()=>I.readCommittedSegment({...f,maxEvents:1}),/LIMIT/));
 await check('partial temp evidence rejected',()=>{const c=cloneFixture(f);fs.writeFileSync(path.join(c.dir,'broken.tmp'),'{}');reseal(c);assert.throws(()=>I.readCommittedSegment(c),/PARTIAL/);});
 await check('duplicate full fallback key rejected',()=>{const p=I.safeRead({...f,continuityProof:null},()=>({complete:true,kind:'candle',trade_date:tradeDate,rows:[a,a],sha256:sha([a,a])}));assert.equal(p.mode,'BLOCKED');});
 const q=n=>({code:'2330',market:'TSE',trade_date:tradeDate,quoteSeenAt:tradeDate+'T01:00:00Z',exchangeTime:tradeDate+'T01:00:00Z',close:100,tradeSerial:n,source:'websocket:trades'}),qf=await fixture('quote',[[{merged:q(1)}],[{previous:q(1),merged:q(2)}]]);
 await check('actual C2 v2 same-price new serial quote symbols',()=>{const p=I.readCommittedSegment(qf);assert.equal(p.events.length,2);assert.deepEqual(p.changedSymbols,['2330']);assert.equal(p.rows[0].tradeSerial,2);});
 await check('original Writer unmodified stage exact initial candle output parity',async()=>{const raw=[a,b,row('3163',0),{...row('3163',1),synthetic:true}],legacy=await originalCandleStage(raw,options);assert.deepEqual(I.writerRows(raw,options),legacy.rows);});
 await check('original Writer rejects bad source, OHLC, future, oddlot exactly',async()=>{const raw=[a,{...b,source:'rest'},{...row('3163'),high:1},{...row('3163'),candleTime:tradeDate+'T05:01:00Z'},{...row('3163'),intradayOddLot:true}];assert.deepEqual(I.writerRows(raw,options),(await originalCandleStage(raw,options)).rows);});
 await check('document existing seeded watermark misses old-minute revision',async()=>{const state={daytradeMotherPoolCandleMirror:{tradeDate,symbols:{2330:{seeded:true,lastCandleTime:b.candleTime}}}},legacy=await originalCandleStage([old,b],options,state);assert.equal(legacy.rows.length,1);assert.equal(legacy.rows[0].candle_time,b.candleTime);assert.equal(I.writerRows([old],options)[0].volume,20);});
 const plan={mode:'DELTA',kind:'candle',rows:[a,b],next:{kind:'candle',epoch:'offline',trade_date:tradeDate,sequence:1,commit_hash:'x'}},file=path.join(scratch,'checkpoint.json'),sink=new Map(),write=async rows=>rows.forEach(r=>sink.set(r.symbol+'|'+r.candle_time,r));
 await check('forming candle cannot advance feed checkpoint',async()=>{await assert.rejects(I.publishOffline({plan:{...plan,rows:[{...a,candleTime:tradeDate+'T05:00:00Z'}]},file,options,write}),/DEFER_OR_INVALIDATION/);assert.equal(fs.existsSync(file),false);});
 await check('quality invalidation cannot leave old DB row silently acknowledged',async()=>{await assert.rejects(I.publishOffline({plan:{...plan,rows:[quality]},file,options,write}),/DEFER_OR_INVALIDATION/);assert.equal(fs.existsSync(file),false);});
 await check('quote publishing remains explicitly blocked',async()=>assert.rejects(I.publishOffline({plan:{...plan,kind:'quote'},file,options,write}),/QUOTE_PUBLICATION/));
 await check('sink failure does not advance checkpoint',async()=>{await assert.rejects(I.publishOffline({plan,file,options,write:async()=>{throw Error('SINK_FAILURE');}}),/SINK/);assert.equal(fs.existsSync(file),false);});
 await check('crash after write replays idempotent rows before checkpoint',async()=>{await assert.rejects(I.publishOffline({plan,file,options,write,fault:()=>{throw Error('CRASH');}}),/CRASH/);assert.equal(sink.size,2);assert.equal(fs.existsSync(file),false);const r=await I.publishOffline({plan,file,options,write});assert.equal(r.written,2);assert.equal(sink.size,2);});
 await check('acknowledged replay dedups sink writes',async()=>assert.equal((await I.publishOffline({plan,file,options,write})).written,0));
 await check('corrupt checkpoint blocks rather than resets',()=>{const c=path.join(scratch,'bad-checkpoint');fs.writeFileSync(c,JSON.stringify({contract:I.CONTRACT,value:{},sha256:'wrong'}));assert.throws(()=>I.loadCheckpoint(c),/CORRUPT/);});
 await check('fsynced unrenamed checkpoint recognizes exact pending and replays sink',async()=>{const f2=path.join(scratch,'crashed');await assert.rejects(I.publishOffline({plan,file:f2,options,write,fault:at=>{if(at==='AFTER_CHECKPOINT_FSYNC')throw Error('CRASH');}}),/CRASH/);assert.equal((await I.publishOffline({plan,file:f2,options,write})).recovered_pending_checkpoint,true);});
 await check('unknown pending checkpoint preserved and blocks before sink',async()=>{const f2=path.join(scratch,'unknown');fs.writeFileSync(f2+'.tmp','{}');await assert.rejects(I.publishOffline({plan,file:f2,options,write:()=>{throw Error('MUST_NOT_WRITE');}}),/UNRECOGNIZED/);assert.equal(fs.readFileSync(f2+'.tmp','utf8'),'{}');});
 await check('fallback throws or malformed row returns BLOCKED',()=>{assert.equal(I.safeRead({...f,continuityProof:null},()=>{throw Error('NO_SNAPSHOT');}).mode,'BLOCKED');assert.equal(I.safeRead({...f,continuityProof:null},()=>({complete:true,kind:'candle',trade_date:tradeDate,rows:[{}],sha256:sha([{}])})).mode,'BLOCKED');});
 await check('STOP prevents even fallback invocation',()=>assert.equal(I.safeRead({...f,stop:true},()=>{throw Error('MUST_NOT_CALL');}).reason,'OPERATOR_STOP'));
 const receipt={phase:2,status:results.every(x=>x.status==='PASS')?'OFFLINE_COMPONENTS_PASS':'FAIL',implementation:'PARTIAL_OFFLINE_ADAPTER',runtime_verified:false,full_writer_parity:false,source_stage_hash:sourceHash,tests:results,fixture_dir:scratch,limitations:['C2 has no production continuity proof; fixed offline segment only','Original seeded Writer intentionally differs for historical revisions; Owner review required before integration','Quotes raw feed verified; quote DB mapping and other Writer outputs unverified','Checkpoint/sink atomicity uses at-least-once replay; DB implementation not connected','Full retained segment independent audit still scans bounded evidence; not a production incremental reader']};fs.writeFileSync(path.join(out,'tests.json'),JSON.stringify(receipt,null,2));if(receipt.status==='FAIL')process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1;});
