-- Dedicated daytrade mother-pool contract views.
-- Purpose: expose the full chain explicitly:
--   full-market quote radar -> mother_pool 300 -> formal priority_top40.
-- Safe to run repeatedly in Supabase SQL Editor or via exec_sql.

begin;


create or replace view public.v_fugle_daytrade_mother_pool as
select
  coalesce(d.trade_date, (q.quote_seen_at at time zone 'Asia/Taipei')::date, (p.updated_at at time zone 'Asia/Taipei')::date) as trade_date,
  p.symbol,
  coalesce(q.name, p.name) as name,
  coalesce(q.market, p.market) as market,
  q.price,
  q.open_price,
  q.previous_close,
  q.change_percent,
  case
    when q.open_price is not null and q.open_price <> 0 and q.price is not null
      then round(((q.price - q.open_price) / q.open_price) * 100, 4)
    else 0::numeric
  end as amplitude_from_open,
  coalesce(q.total_volume, 0) as total_volume,
  coalesce(q.trade_value, 0) as trade_value,
  coalesce(d.avg_volume5, d.avg5_volume, 0) as avg5_volume,
  coalesce(nullif(p.payload ->> 'score', '')::numeric, 0) as mother_pool_score,
  coalesce(nullif(p.payload ->> 'priorityScore', '')::numeric, nullif(p.payload ->> 'score', '')::numeric, 0) as priority_score,
  p.priority_rank,
  p.priority_rank as mother_pool_rank,
  coalesce(nullif(p.payload ->> 'isStrongGroupLeader', '')::boolean, false) as is_strong_group_leader,
  coalesce(nullif(p.payload ->> 'strongGroupLeaderScore', '')::numeric, 0) as strong_group_leader_score,
  coalesce(nullif(p.payload ->> 'futopt0846Ready', '')::boolean, false) as futopt_0846_ready,
  coalesce(nullif(p.payload ->> 'futopt0846Score', '')::numeric, 0) as futopt_0846_score,
  coalesce(nullif(p.payload ->> 'turnoverRate3d', '')::numeric, 0) as turnover_rate_3d,
  coalesce(nullif(p.payload ->> 'turnoverRate5d', '')::numeric, 0) as turnover_rate_5d,
  coalesce(nullif(p.payload ->> 'turnoverScore', '')::numeric, 0) as turnover_score,
  coalesce(nullif(p.payload ->> 'marginDecreasePriceStrong', '')::boolean, false) as margin_decrease_price_strong,
  coalesce(nullif(p.payload ->> 'marginDecreasePriceStrongScore', '')::numeric, 0) as margin_decrease_price_strong_score,
  coalesce(nullif(p.payload ->> 'marginShortSyncPriceStrong', '')::boolean, false) as margin_short_sync_price_strong,
  coalesce(nullif(p.payload ->> 'marginShortSyncPriceStrongScore', '')::numeric, 0) as margin_short_sync_price_strong_score,
  coalesce(nullif(p.payload ->> 'exDividendRisk', '')::boolean, false) as ex_dividend_risk,
  coalesce(nullif(p.payload ->> 'nextDaySellRisk', '')::boolean, false) as next_day_sell_risk,
  coalesce(nullif(p.payload ->> 'daytradeRiskPenalty', '')::numeric, 0) as daytrade_risk_penalty,
  p.priority_rank as mother_rank,
  p.priority_reason as mother_reason,
  p.source as mother_source,
  p.updated_at as mother_updated_at,
  coalesce(nullif(p.payload ->> 'score', '')::numeric, 0) as mother_score,
  coalesce(p.payload ->> 'motherPoolRuleVersion', 'daytrade_mother_pool_base_filter_20260727') as mother_pool_rule_version,
  coalesce(p.payload -> 'motherPoolRuleHits', '[]'::jsonb) as mother_pool_rule_hits,
  coalesce(p.payload -> 'motherPoolMetrics', '{}'::jsonb) as mother_pool_metrics,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,tradeValue}', '')::numeric, 0) as mother_metric_trade_value,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,totalVolume}', '')::numeric, 0) as mother_metric_total_volume,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,changePercent}', '')::numeric, 0) as mother_metric_change_percent,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,avgVolume5}', '')::numeric, 0) as mother_metric_avg_volume5,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,turnoverRate}', '')::numeric, 0) as turnover_rate,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,quoteFresh}', '')::boolean, false) as quote_fresh_at_rank,
  q.quote_seen_at,
  q.updated_at as quote_updated_at,
  coalesce(extract(epoch from (now() - q.quote_seen_at))::integer, 999999) as quote_age_seconds,
  q.change_percent as live_change_percent,
  q.total_volume as live_total_volume,
  q.trade_value as live_trade_value,
  d.trade_date as daily_volume_trade_date,
  coalesce(d.avg_volume5, d.avg5_volume, 0) as live_avg_volume5,
  case
    when p.priority_rank <= 40 then true
    else false
  end as in_formal_priority_top40,
  case
    when q.symbol is null then 'quote_missing'
    when coalesce(extract(epoch from (now() - q.quote_seen_at))::integer, 999999) > 120 then 'quote_stale'
    when coalesce(d.avg_volume5, d.avg5_volume, 0) <= 0 then 'daily_volume_missing'
    else 'ready'
  end as mother_readiness_status,
  (
    p.priority_rank <= 40
    and p.payload ->> 'basePoolEligible' = 'true'
    and q.symbol is not null
    and coalesce(extract(epoch from (now() - q.quote_seen_at))::integer, 999999) <= 120
    and coalesce(d.avg_volume5, d.avg5_volume, 0) > 0
  ) as is_formal_entry_eligible,
  'fugle_daytrade_source'::text as source_name,
  greatest(p.updated_at, coalesce(q.updated_at, p.updated_at), coalesce(d.updated_at, p.updated_at)) as updated_at,
  p.payload,
  coalesce(d.trade_date, (p.updated_at at time zone 'Asia/Taipei')::date) as source_trade_date,
  (q.quote_seen_at at time zone 'Asia/Taipei')::date as quote_trade_date,
  (p.updated_at at time zone 'Asia/Taipei')::date as pool_updated_trade_date,
  'live_quote_with_previous_daily_volume_basis'::text as pool_context,
  coalesce(d.avg_volume5, d.avg5_volume, 0) as avg_volume5,
  q.high_price as high_price,
  q.low_price as low_price,
  s.latest_candle_time,
  coalesce(s.latest_candle_age_seconds, 999999)::integer as intraday_1m_stale_seconds,
  coalesce(s.ready_ma5, false) as ready_ma5,
  coalesce(s.ready_ma10, false) as ready_ma10,
  coalesce(s.ready_ma30, false) as ready_ma30,
  s.ma5 as ma5,
  s.ma10 as ma10,
  s.ma35 as ma35,
  coalesce(s.ma5_ma10_ma35_bullish, false) as ma5_ma10_ma35_bullish,
  coalesce(s.ma5_ma10_ma35_bullish, false) as ma_bullish_alignment,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,volumeRatio5}', '')::numeric,
    case when coalesce(d.avg_volume5, d.avg5_volume, 0) > 0
      then coalesce(q.total_volume, 0) / coalesce(d.avg_volume5, d.avg5_volume, 1)
      else 0 end) as volume_vs_avg5_ratio,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,volumeRank}', '')::integer, 0) as volume_rank,
  coalesce(si.relative_volume_5m, nullif(p.payload #>> '{motherPoolMetrics,relativeVolume5m}', '')::numeric, 0) as relative_volume_5m,
  coalesce(nullif(si.recent_1m_volume_trend, ''), nullif(p.payload #>> '{motherPoolMetrics,recent1mVolumeTrend}', ''), 'unknown')::text as recent_1m_volume_trend,
  coalesce(si.ma5_rising, nullif(p.payload #>> '{motherPoolMetrics,ma5Rising}', '')::boolean, false) as ma5_rising,
  coalesce(si.ma10_rising, nullif(p.payload #>> '{motherPoolMetrics,ma10Rising}', '')::boolean, false) as ma10_rising,
  coalesce(si.ma30_rising, nullif(p.payload #>> '{motherPoolMetrics,ma30Rising}', '')::boolean, false) as ma30_rising,
  coalesce(si.ma35_rising, nullif(p.payload #>> '{motherPoolMetrics,ma35Rising}', '')::boolean, false) as ma35_rising,
  coalesce(q.price >= q.open_price and q.open_price > 0, false) as above_open_price,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,aboveVwap}', '')::boolean, false) as above_vwap,
  coalesce(q.price >= q.high_price * 0.985 and q.high_price > 0, false) as near_day_high,
  case when s.ma5 > 0 and q.price is not null then ((q.price - s.ma5) / s.ma5) * 100 else 0 end as distance_from_ma5_percent,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,sectorName}', ''), '')::text as sector_name,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,sectorStrengthScore}', '')::numeric, 0) as sector_strength_score,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,sectorMemberActiveCount}', '')::integer, 0) as sector_member_active_count,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,futoptSyncScore}', '')::numeric, 0) as futopt_sync_score,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,liquidityScore}', '')::numeric, 0) as liquidity_score,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,spreadScore}', '')::numeric, 0) as spread_score,
  coalesce(nullif(p.payload #>> '{motherPoolMetrics,fakeStrengthPenalty}', '')::numeric, 0) as fake_strength_penalty,
  s.latest_candle_time as latest_1m_time,
  s.ma30 as ma30
from public.fugle_daytrade_priority_pool p
left join public.fugle_daytrade_quotes_live q on q.symbol = p.symbol
left join public.fugle_daytrade_daily_volume_avg d on d.symbol = p.symbol
left join public.v_fugle_daytrade_intraday_1m_status s on s.symbol = p.symbol
left join public.v_fugle_daytrade_intraday_1m_technical_status si on si.symbol = p.symbol
left join public.source_status ss on ss.source_name = 'fugle_daytrade_source'
where p.payload ->> 'basePoolEligible' = 'true';

create or replace view public.v_fugle_daytrade_formal_priority_top40 as
select
  trade_date,
  symbol,
  name,
  market,
  price,
  open_price,
  previous_close,
  change_percent,
  amplitude_from_open,
  total_volume,
  trade_value,
  avg5_volume,
  mother_pool_score,
  priority_score,
  priority_rank,
  mother_pool_rank,
  is_strong_group_leader,
  strong_group_leader_score,
  futopt_0846_ready,
  futopt_0846_score,
  turnover_rate_3d,
  turnover_rate_5d,
  turnover_score,
  margin_decrease_price_strong,
  margin_decrease_price_strong_score,
  margin_short_sync_price_strong,
  margin_short_sync_price_strong_score,
  ex_dividend_risk,
  next_day_sell_risk,
  daytrade_risk_penalty,
  mother_rank,
  mother_reason,
  mother_source,
  mother_updated_at,
  mother_score,
  mother_pool_rule_version,
  mother_pool_rule_hits,
  mother_pool_metrics,
  mother_metric_trade_value,
  mother_metric_total_volume,
  mother_metric_change_percent,
  mother_metric_avg_volume5,
  turnover_rate,
  quote_fresh_at_rank,
  quote_seen_at,
  quote_updated_at,
  quote_age_seconds,
  live_change_percent,
  live_total_volume,
  live_trade_value,
  daily_volume_trade_date,
  live_avg_volume5,
  in_formal_priority_top40,
  mother_readiness_status,
  is_formal_entry_eligible,
  source_name,
  updated_at,
  payload,
  source_trade_date,
  quote_trade_date,
  pool_updated_trade_date,
  pool_context,
  avg5_volume as avg_volume5,
  high_price,
  low_price,
  latest_candle_time,
  intraday_1m_stale_seconds,
  ready_ma5,
  ready_ma10,
  ready_ma30,
  ma5,
  ma10,
  ma35,
  ma5_ma10_ma35_bullish,
  ma_bullish_alignment,
  volume_vs_avg5_ratio,
  volume_rank,
  relative_volume_5m,
  recent_1m_volume_trend,
  ma5_rising,
  ma10_rising,
  ma30_rising,
  ma35_rising,
  above_open_price,
  above_vwap,
  near_day_high,
  distance_from_ma5_percent,
  sector_name,
  sector_strength_score,
  sector_member_active_count,
  futopt_sync_score,
  liquidity_score,
  spread_score,
  fake_strength_penalty,
  latest_1m_time,
  ma30
from (
  select
    mp.*,
    row_number() over (order by mother_rank asc, symbol asc) as rn
  from public.v_fugle_daytrade_mother_pool mp
  where in_formal_priority_top40 is true
) ranked
where rn <= 40
order by rn asc, mother_rank asc, symbol asc;

create or replace view public.v_fugle_daytrade_priority_top40 as
select
  trade_date,
  symbol,
  name,
  market,
  price,
  open_price,
  previous_close,
  change_percent,
  amplitude_from_open,
  total_volume,
  trade_value,
  avg5_volume,
  mother_pool_score,
  priority_score,
  priority_rank,
  mother_pool_rank,
  is_strong_group_leader,
  strong_group_leader_score,
  futopt_0846_ready,
  futopt_0846_score,
  turnover_rate_3d,
  turnover_rate_5d,
  turnover_score,
  margin_decrease_price_strong,
  margin_decrease_price_strong_score,
  margin_short_sync_price_strong,
  margin_short_sync_price_strong_score,
  ex_dividend_risk,
  next_day_sell_risk,
  daytrade_risk_penalty,
  mother_rank,
  mother_reason,
  mother_source,
  mother_updated_at,
  mother_score,
  mother_pool_rule_version,
  mother_pool_rule_hits,
  mother_pool_metrics,
  mother_metric_trade_value,
  mother_metric_total_volume,
  mother_metric_change_percent,
  mother_metric_avg_volume5,
  turnover_rate,
  quote_fresh_at_rank,
  quote_seen_at,
  quote_updated_at,
  quote_age_seconds,
  live_change_percent,
  live_total_volume,
  live_trade_value,
  daily_volume_trade_date,
  live_avg_volume5,
  in_formal_priority_top40,
  mother_readiness_status,
  is_formal_entry_eligible,
  source_name,
  updated_at,
  payload,
  source_trade_date,
  quote_trade_date,
  pool_updated_trade_date,
  pool_context,
  avg5_volume as avg_volume5,
  high_price,
  low_price,
  latest_candle_time,
  intraday_1m_stale_seconds,
  ready_ma5,
  ready_ma10,
  ready_ma30,
  ma5,
  ma10,
  ma35,
  ma5_ma10_ma35_bullish,
  ma_bullish_alignment,
  volume_vs_avg5_ratio,
  volume_rank,
  relative_volume_5m,
  recent_1m_volume_trend,
  ma5_rising,
  ma10_rising,
  ma30_rising,
  ma35_rising,
  above_open_price,
  above_vwap,
  near_day_high,
  distance_from_ma5_percent,
  sector_name,
  sector_strength_score,
  sector_member_active_count,
  futopt_sync_score,
  liquidity_score,
  spread_score,
  fake_strength_penalty,
  latest_1m_time,
  ma30
from (
  select
    mp.*,
    row_number() over (order by mother_pool_rank asc, symbol asc) as rn
  from public.v_fugle_daytrade_mother_pool mp
  where in_formal_priority_top40 is true
) ranked
where rn <= 40
order by rn asc, mother_pool_rank asc, symbol asc;

grant select on public.v_fugle_daytrade_mother_pool to anon, authenticated, service_role;
grant select on public.v_fugle_daytrade_formal_priority_top40 to anon, authenticated, service_role;
grant select on public.v_fugle_daytrade_priority_top40 to anon, authenticated, service_role;
grant select on public.v_fugle_daytrade_mother_pool_contract_health to anon, authenticated, service_role;

commit;
