-- Supabase frontend readback tables, 2026-06-11.
-- Purpose:
--   These tables are used by frontend/deploy verification readback.
--   They store the latest JSON payloads generated by strategy jobs.
--
-- Run once in Supabase SQL Editor:
--   https://supabase.com/dashboard/project/cpmpfhbzutkiecccekfr/sql/new

create table if not exists public.strategy2_latest (
  id text primary key default 'latest',
  date text,
  updated_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  entry_count integer not null default 0,
  record_count integer not null default 0,
  event_count integer not null default 0
);

create table if not exists public.strategy1_open_buy_latest (
  id text primary key default 'latest',
  date text,
  updated_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  match_count integer not null default 0,
  scanned_count integer not null default 0,
  total_count integer not null default 0
);

create table if not exists public.fuman_realtime_radar_cache (
  id text primary key default 'latest',
  updated_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

comment on table public.strategy2_latest is
  'Latest strategy2 intraday report payload for frontend/Supabase readback.';

comment on table public.strategy1_open_buy_latest is
  'Latest strategy1 open-buy payload for frontend/Supabase readback.';

comment on table public.fuman_realtime_radar_cache is
  'Latest realtime radar payload for frontend/Supabase readback.';

create index if not exists idx_strategy2_latest_updated_at
  on public.strategy2_latest (updated_at desc);

create index if not exists idx_strategy1_open_buy_latest_updated_at
  on public.strategy1_open_buy_latest (updated_at desc);

create index if not exists idx_fuman_realtime_radar_cache_updated_at
  on public.fuman_realtime_radar_cache (updated_at desc);

alter table public.strategy2_latest enable row level security;
alter table public.strategy1_open_buy_latest enable row level security;
alter table public.fuman_realtime_radar_cache enable row level security;

drop policy if exists "read strategy2 latest" on public.strategy2_latest;
drop policy if exists "anon upsert strategy2 latest" on public.strategy2_latest;
drop policy if exists "read strategy1 open buy latest" on public.strategy1_open_buy_latest;
drop policy if exists "read fuman realtime radar cache" on public.fuman_realtime_radar_cache;

create policy "read strategy2 latest"
on public.strategy2_latest
for select
to anon
using (true);

create policy "anon upsert strategy2 latest"
on public.strategy2_latest
for all
to anon
using (id = 'latest')
with check (id = 'latest');

create policy "read strategy1 open buy latest"
on public.strategy1_open_buy_latest
for select
to anon
using (true);

create policy "read fuman realtime radar cache"
on public.fuman_realtime_radar_cache
for select
to anon
using (true);

grant select, insert, update on public.strategy2_latest to anon;
grant select on public.strategy1_open_buy_latest to anon;
grant select on public.fuman_realtime_radar_cache to anon;

grant select, insert, update, delete on public.strategy2_latest to service_role;
grant select, insert, update, delete on public.strategy1_open_buy_latest to service_role;
grant select, insert, update, delete on public.fuman_realtime_radar_cache to service_role;

-- Optional smoke test after strategy jobs write rows:
-- select id, date, updated_at, entry_count, record_count, event_count
-- from public.strategy2_latest
-- where id = 'latest';
--
-- select id, date, updated_at, match_count, scanned_count, total_count
-- from public.strategy1_open_buy_latest
-- where id = 'latest';
--
-- select id, updated_at, jsonb_typeof(payload) as payload_type
-- from public.fuman_realtime_radar_cache
-- where id = 'latest';
