'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const {createOracle,hash}=require('./original-oracle.cjs');
const {IncrementalDiscovery,classifyCandle}=require('./incremental-discovery.cjs');
const {fixture,quote,asOf}=require('./fixture.cjs');
const results=[],out=path.join(__dirname,'receipts');fs.mkdirSync(out,{recursive:true});
function test(name,fn){try{fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});}}
const incremental=createOracle({memoize:true}),full=createOracle(),engine=new IncrementalDiscovery({oracle:incremental});
let seq=0;
function batch(events=[],extra={}){return {epoch:'isolated-epoch',tradeDate:'2026-10-08',sequence:++seq,continuity:'CONTIGUOUS',asOf,events,...extra};}
function parity(result,time=asOf){assert.equal(result.status,'OFFLINE_EVALUATED',result.reason);const oracle=full.evaluate(engine.input(engine.state),{asOf:time});assert.deepEqual(result.output.rows,oracle.rows);assert.deepEqual(result.output.metadata,oracle.metadata);return result;}
const base=fixture(300);base.quoteMap[299][1]=quote('1299',30,1);engine.baseline(base);
test('original function full baseline / all-market denominator',()=>{const r=parity(engine.process(batch()));assert.equal(r.all_market_observed,300);assert(!r.output.rows.some(x=>x.symbol==='1299'));});
test('12:45 new strength outside original membership admitted by unchanged rules',()=>{const r=parity(engine.process(batch([{resource:'quoteMap',symbol:'1299',value:quote('1299',105,20000)}])));assert(r.admissions.some(x=>x.symbol==='1299'&&x.type==='LATE_ADMISSION'));assert.equal(r.output.metrics.metric_calls,1);assert.equal(r.output.metrics.metric_hits,299);});
test('same batch exact replay does not reevaluate or readmit',()=>{const b=batch();const r=parity(engine.process(b));assert.equal(engine.process(b).status,'REPLAY_DEDUP');assert.equal(r.admissions.length,0);});
test('unchanged payload deduplicates',()=>{const r=parity(engine.process(batch([{resource:'quoteMap',symbol:'1299',value:quote('1299',105,20000)}])));assert.equal(r.duplicates,1);assert.equal(r.output.metrics.metric_calls,0);});
test('exit obeys original price gate',()=>{const r=parity(engine.process(batch([{resource:'quoteMap',symbol:'1299',value:quote('1299',30,20000)}])));assert(r.exits.includes('1299'));});
test('re-entry after exit is observable and unique',()=>{const r=parity(engine.process(batch([{resource:'quoteMap',symbol:'1299',value:quote('1299',107,30000)}])));assert.equal(r.admissions.filter(x=>x.symbol==='1299').length,1);});
test('revised derived indicator input invalidates symbol; raw K derivation excluded',()=>{const value={...new Map(engine.state.supplementalMaps.intradayMap).get('1299'),ma20:120};const r=parity(engine.process(batch([{resource:'intradayMap',symbol:'1299',value}])));assert.equal(r.output.metrics.metric_calls,1);assert(r.output.rows.find(x=>x.symbol==='1299').payload.fast_remove);});
test('cross-symbol ranks remain exactly full recomputation',()=>{const r=parity(engine.process(batch([{resource:'quoteMap',symbol:'1000',value:quote('1000',110,999999)}])));assert.equal(r.output.metadata.intradayTurnoverRanking.rows[0].symbol,'1000');});
test('clock-only expiry refreshes all symbols rather than stale memo',()=>{const time='2026-10-08T04:48:00.000Z';const r=parity(engine.process(batch([],{asOf:time})),time);assert.equal(r.output.metrics.metric_calls,300);assert(r.exits.length>0);});
test('NO_TRADE requires independent resolver and never bypasses original gate',()=>{const evidence={noTradeVerified:true,nativeEvidenceHash:'fixture',continuousObservation:true,unpublishedEvent:false};assert.equal(classifyCandle(evidence,()=>true),'NO_TRADE_OBSERVED');assert.equal(classifyCandle(evidence),'MISSING_OR_UNKNOWN');assert.equal(classifyCandle(evidence,()=>false),'MISSING_OR_UNKNOWN');assert.equal(classifyCandle({present:true}),'PRESENT');});
test('sequence gap preserves checkpoint',()=>{const before=engine.checkpoint();const r=engine.process(batch([],{sequence:9999}));seq--;assert.equal(r.reason,'SEQUENCE_GAP_OR_CONFLICT');assert.deepEqual(engine.checkpoint(),before);});
test('GAP requires full verified baseline; no silent continuation',()=>{const before=engine.checkpoint();const r=engine.process(batch([],{continuity:'GAP'}));seq--;assert.equal(r.reason,'FULL_BASELINE_RECOVERY_REQUIRED');assert.deepEqual(engine.checkpoint(),before);});
test('wrong epoch refused',()=>{assert.equal(engine.process(batch([],{epoch:'wrong'})).reason,'IDENTITY_MISMATCH');seq--;});
test('out-of-universe change cannot narrow or expand universe silently',()=>{const before=engine.checkpoint();const r=engine.process(batch([{resource:'quoteMap',symbol:'9999',value:quote('9999')} ],{asOf:engine.state.lastAsOf}));seq--;assert.equal(r.reason,'RESOURCE_OR_UNIVERSE_INVALID');assert.deepEqual(engine.checkpoint(),before);});
test('bounded event count failure is atomic',()=>{const r=engine.process(batch(Array.from({length:5001},()=>({resource:'quoteMap',symbol:'1000',value:null}))));seq--;assert.equal(r.reason,'CAPACITY_LIMIT');});
test('checkpoint crash restart preserves membership and replay dedup',()=>{const saved=engine.checkpoint(),restarted=new IncrementalDiscovery({oracle:createOracle({memoize:true})});restarted.restore(saved);assert.deepEqual(restarted.checkpoint(),saved);const r=restarted.process({epoch:'isolated-epoch',tradeDate:'2026-10-08',sequence:saved.payload.state.sequence+1,continuity:'CONTIGUOUS',asOf:saved.payload.state.lastAsOf,events:[]});assert.equal(r.status,'OFFLINE_EVALUATED');assert.equal(r.output.metrics.metric_calls,300);});
test('corrupt checkpoint refused',()=>{const bad=engine.checkpoint();bad.payload.state.sequence++;assert.throws(()=>engine.restore(bad),/CHECKPOINT_HASH_MISMATCH/);});
test('oracle failure leaves state unchanged',()=>{const before=engine.checkpoint();const r=engine.process(batch([],{asOf:'invalid'}));seq--;assert.equal(r.status,'BLOCKED');assert.deepEqual(engine.checkpoint(),before);});
test('STOP does not consume new work',()=>{engine.stop();assert.equal(engine.process(batch()).status,'STOPPED');});
test('offline oracle has no network/process/write side effects',()=>{assert.deepEqual(incremental.audit.denied_operations,[]);assert.deepEqual(full.audit.denied_operations,[]);});
test('equivalent UTC and Taipei admission timestamps',()=>{const values=[];for(const time of [asOf,'2026-10-08T12:45:00.000+08:00']){const e=new IncrementalDiscovery({oracle:createOracle({memoize:true})});e.baseline(fixture(1));values.push(e.process({epoch:'isolated-epoch',tradeDate:'2026-10-08',sequence:1,continuity:'CONTIGUOUS',asOf:time,events:[]}).admissions[0].type);}assert.deepEqual(values,['LATE_ADMISSION','LATE_ADMISSION']);});
test('cross-date as-of is refused',()=>{const e=new IncrementalDiscovery({oracle:createOracle()});e.baseline(fixture(1));assert.equal(e.process({epoch:'isolated-epoch',tradeDate:'2026-10-08',sequence:1,continuity:'CONTIGUOUS',asOf:'2026-10-09T04:45:00Z',events:[]}).reason,'ASOF_DATE_INVALID');});
test('immediate 10:00 admission uses unchanged function',()=>{const snapshot=fixture(2),time='2026-10-08T02:00:00Z';snapshot.quoteMap=snapshot.quoteMap.map(([s])=>[s,quote(s,105,20000,time)]);const e=new IncrementalDiscovery({oracle:createOracle({memoize:true})});e.baseline(snapshot);const result=e.process({epoch:snapshot.epoch,tradeDate:snapshot.tradeDate,sequence:1,continuity:'CONTIGUOUS',asOf:time,events:[]});assert.equal(result.admissions.length,2);assert(result.admissions.every(x=>x.type==='ADMISSION'));});
test('deterministic mixed quote/indicator/time replay matches full oracle',()=>{const e=new IncrementalDiscovery({oracle:createOracle({memoize:true})}),o=createOracle();e.baseline(fixture(160));for(let i=0;i<16;i++){const time=new Date(Date.parse(asOf)+Math.floor(i/4)*1000).toISOString(),symbol=String(1000+(i*37)%160),event=i%3===0?{resource:'intradayMap',symbol,value:{ma3:105,ma5:103,ma10:101,ma20:i%2?120:99}}:{resource:'quoteMap',symbol,value:quote(symbol,i%5===0?30:104+i,10000+i*100,time)};const r=e.process({epoch:'isolated-epoch',tradeDate:'2026-10-08',sequence:i+1,continuity:'CONTIGUOUS',asOf:time,events:[event]});assert.equal(r.status,'OFFLINE_EVALUATED');const reference=o.evaluate(e.input(e.state),{asOf:time});assert.deepEqual(r.output.rows,reference.rows);assert.deepEqual(r.output.metadata,reference.metadata);}});
const report={phase:3,generated_at:new Date().toISOString(),scope:'ISOLATED_SYNTHETIC_INPUTS_WITH_ACTUAL_ORIGINAL_BUILD_PRIORITY_POOL',source:full.source,tests:results,passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length,runtime_verified:false};
fs.writeFileSync(path.join(out,'correctness.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));process.exitCode=report.failed?1:0;

