'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {Consumer,frame}=require('./consumer.cjs');
const {strategy3,strategyCore,makeWater,telegram,deepAnalysis,sha}=require('./original-adapters.cjs');
const {produce}=require('../../lib/telegram-detectors/natural-source-runner.cjs');
const {fixture}=require('../../lib/telegram-detectors/level-gate-fixture.cjs');
const planContract=require('../../lib/telegram-detectors/premarket-plan-contract.cjs');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'phase4-offline-'));
const date='2026-10-06',identity='fixture-snapshot-1',epoch='fixture-epoch-1';
const gate=require('./fixtures.cjs').gate(identity);
function bars(s,n=22,start='12:38',d=date){return Array.from({length:n},(_,i)=>{const t=Date.parse(`${d}T${start}:00+08:00`)+i*60000,p=100+i*0.01;return {stock_id:s,trade_date:d,timestamp:new Date(t).toISOString(),open:p,high:p+0.1,low:p-0.1,close:p,volume_raw:i===n-1?50:10,volume_raw_unit:'LOTS',complete:true,is_synthetic:false,available_at:new Date(t+60000).toISOString(),source:'Fugle.websocket.candles.TSE_OTC'};});}
function data(s,n=22){return {current:bars(s,n),history:[],pool:{name:s,trade_date:date},quote:{price:106,previous_close:100,change_percent:6,limit_up_price:110},technical:{source_ready:false},atr:{source_ready:false}};}
function bf(s,f){return {symbol:s,trade_date:date,identity,complete:true,data:data(s)};}
function f(seq,events,patch={}){return frame({epoch,identity,trade_date:date,sequence:seq,status:'DURABLE_COMMITTED',as_of:date+'T13:00:00+08:00',events,...patch});}
function client(name,limits){return new Consumer({directory:path.join(dir,name),tradeDate:date,identity,epoch,limits});}
function resultRows(c){return Object.values(c.state.strategy).sort((a,b)=>a.rank-b.rank);}
const tests=[];async function test(name,fn){const t=performance.now();await fn();tests.push({name,status:'PASS',duration_ms:performance.now()-t});}
async function main(){
await test('bounded formatter VM produces exact unmodified native-Intl scanner output',async()=>{const state={trade_date:date,identity,symbols:{1001:data('1001'),1002:data('1002')}};const symbols=['1001','1002'];const readers=[async()=>makeWater(state,symbols,gate),async()=>new Map(),async()=>new Map()];const a=await strategyCore(date,{memoizeFormatter:false}).fn(...readers),b=await strategyCore(date).fn(...readers);assert.deepEqual(JSON.parse(JSON.stringify(a.results)),JSON.parse(JSON.stringify(b.results)));});
await test('late admission backfill exact Strategy3 full-core result parity',async()=>{const c=client('parity');await c.process(f(1,[{kind:'ADMIT',symbol:'1001'},{kind:'ADMIT',symbol:'1002'}]),{backfill:bf,gate});const full=await strategy3(c.state,Object.keys(c.state.symbols),gate);assert.deepEqual(resultRows(c),full.results);assert.equal(full.results.length,2);});
await test('quote change reranks globally and keeps unchanged stock results',async()=>{const c=client('parity');await c.process(f(2,[{kind:'QUOTE',symbol:'1001',payload:{price:108,previous_close:100,change_percent:8,limit_up_price:110}}]),{gate});const full=await strategy3(c.state,Object.keys(c.state.symbols),gate);assert.deepEqual(resultRows(c),full.results);});
await test('full scanner water Gate fail closed no commit',async()=>{const c=client('parity'),before=sha(JSON.stringify(c.state));await assert.rejects(c.process(f(3,[{kind:'QUOTE',symbol:'1001',payload:{price:107}}]),{gate:{...gate,ok:false}}),/UPSTREAM_GATE/);assert.equal(sha(JSON.stringify(c.state)),before);});
await test('same frame restart replay dedup',async()=>{const c=client('replay'),fr=f(1,[{kind:'ADMIT',symbol:'1001'}]);await c.process(fr,{backfill:bf,gate});const b=client('replay');assert.equal((await b.process(fr,{gate})).status,'REPLAY_DEDUP');});
await test('same sequence conflicting content refused',async()=>{const c=client('replay');await assert.rejects(c.process(f(1,[]),{gate}),/REPLAY_CONFLICT/);});
await test('sequence gap requires recovery',async()=>{await assert.rejects(client('replay').process(f(3,[]),{gate}),/SEQUENCE_GAP/);});
await test('C2 GAP never advances checkpoint',async()=>{const c=client('replay');await assert.rejects(c.process(f(2,[],{status:'GAP'}),{gate}),/GAP_FULL_RECOVERY/);assert.equal(c.state.seq,1);});
await test('epoch and date changes require baseline recovery',async()=>{await assert.rejects(client('replay').process(f(2,[],{epoch:'new'}),{gate}),/IDENTITY_RECOVERY/);assert.throws(()=>new Consumer({directory:path.join(dir,'replay'),tradeDate:'2026-10-07',identity,epoch}),/IDENTITY_RECOVERY/);});
await test('hash tamper refused',async()=>{const x=f(2,[]);x.as_of=date+'T13:01:00+08:00';await assert.rejects(client('replay').process(x,{gate}),/FRAME_HASH/);});
await test('late backfill absent wrong identity or incomplete refuses admission',async()=>{for(const b of [null,{symbol:'1001',trade_date:date,identity:'wrong',complete:true},{symbol:'1001',trade_date:date,identity,complete:false}])await assert.rejects(client('missing').process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:()=>b,gate}),/BACKFILL_UNVERIFIED/);});
await test('duplicate backfill minutes reject before checkpoint',async()=>{await assert.rejects(client('dup').process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:(s)=>{const b=bf(s);b.data.current.push(b.data.current[0]);return b;},gate}),/BACKFILL_CONFLICT/);});
await test('missing K is recorded not replaced by zero K',async()=>{const c=client('missingk');await c.process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:s=>{const b=bf(s);b.data.current.splice(-1);b.data.gap='MISSING_1259';return b;},gate});assert.equal(resultRows(c).length,0);assert.equal(c.state.symbols['1001'].current.length,21);});
await test('crash before rename leaves checkpoint old; replay recovers once',async()=>{const c=client('crash'),a=f(1,[{kind:'ADMIT',symbol:'1001'}]);await assert.rejects(c.process(a,{backfill:bf,gate,fault:'BEFORE_RENAME'}),/INJECTED_CRASH/);const r=client('crash');assert.equal(r.state.seq,0);await r.process(a,{backfill:bf,gate});assert.equal(r.state.seq,1);});
await test('crash after rename retains result and checkpoint atomicity',async()=>{const c=client('crash'),a=f(2,[]);await assert.rejects(c.process(a,{gate,fault:'AFTER_RENAME'}),/INJECTED_CRASH/);const r=client('crash');assert.equal(r.state.seq,2);assert.equal((await r.process(a,{gate})).status,'REPLAY_DEDUP');});
await test('consumer evaluation failure preserves old checkpoint',async()=>{const c=client('crash');await assert.rejects(c.process(f(3,[]),{gate,fault:'BEFORE_EVALUATE'}),/INJECTED_CONSUMER/);assert.equal(c.state.seq,2);});
await test('checkpoint payload corruption fails closed',async()=>{const c=client('corrupt');await c.process(f(1,[]),{gate});const x=JSON.parse(fs.readFileSync(c.file));x.payload.seq=99;fs.writeFileSync(c.file,JSON.stringify(x));assert.throws(()=>client('corrupt'),/STATE_HASH/);});
await test('STOP prevents calculation and commit',async()=>{const c=client('stop');c.stop();await assert.rejects(c.process(f(1,[]),{gate}),/STOPPED/);});
await test('limits frame/symbol/history/state/outbox bounded fail closed',async()=>{await assert.rejects(client('limitframe',{events:0}).process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:bf,gate}),/FRAME_CAPACITY/);await assert.rejects(client('limitsymbol',{symbols:0}).process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:bf,gate}),/SYMBOL_CAPACITY/);await assert.rejects(client('limitbar',{bars:1}).process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:bf,gate}),/BAR_CAPACITY/);await assert.rejects(client('limitbytes',{stateBytes:1}).process(f(1,[]),{gate}),/STATE_CAPACITY/);});
await test('quote-only and transport-only no Discovery re-evaluation',async()=>{const c=client('quoteonly');await c.process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:bf,gate});for(const [i,e]of [[2,{kind:'QUOTE',symbol:'1001',payload:{price:106}}],[3,{kind:'TRANSPORT',symbol:'1001'}]])assert.deepEqual((await c.process(f(i,[e]),{gate})).discovery,[]);});
await test('old-minute revision updates current result with exact detector parity',async()=>{const c=client('oldrev');await c.process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:bf,gate});const b={...c.state.symbols['1001'].current[4],volume_raw:200};const r=await c.process(f(2,[{kind:'CANDLE',symbol:'1001',payload:b}]),{gate});assert.deepEqual(r.discovery,['1001']);assert.deepEqual(c.state.telegram['1001'],telegram(c.state,['1001'],date+'T13:00:00+08:00'));});
await test('same minute duplicate no recalculation',async()=>{const c=client('oldrev');const b=c.state.symbols['1001'].current[4];assert.deepEqual((await c.process(f(3,[{kind:'CANDLE',symbol:'1001',payload:b}]),{gate})).discovery,[]);});
await test('future and wrong-day K rejected',async()=>{for(const patch of [{timestamp:date+'T13:00:00+08:00'},{trade_date:'2026-10-05'}]){const c=client('oldrev'),b={...c.state.symbols['1001'].current[4],...patch};await assert.rejects(c.process(f(4,[{kind:'CANDLE',symbol:'1001',payload:b}]),{gate}),/UNCOMPLETED_CANDLE|CANDLE_IDENTITY/);}});
await test('exit removes results; reentry requires fresh frozen backfill',async()=>{const c=client('oldrev');await c.process(f(4,[{kind:'EXIT',symbol:'1001'}]),{gate});assert.equal(resultRows(c).length,0);await c.process(f(5,[{kind:'ADMIT',symbol:'1001'}]),{backfill:bf,gate});assert.equal(resultRows(c).length,1);});
await test('actual natural runner event parity including native source filters fixture',async()=>{const r=path.join(dir,'natural'),d=data('1001');fs.mkdirSync(path.join(r,'cache/intraday'),{recursive:true});fs.writeFileSync(path.join(r,'cache/intraday/fugle-daytrade-ws-candles-v2.json'),JSON.stringify({candles:d.current.map(b=>({symbol:b.stock_id,market:'TSE',tradeDate:b.trade_date,candleTime:b.timestamp,open:b.open,high:b.high,low:b.low,close:b.close,volume:b.volume_raw,synthetic:false,websocketRow:true,restRepairRow:false,sourceChannel:'candles',candleSeenAt:b.available_at,volumeStrategyUsable:true}))}));const full=produce({runtimeRoot:r,now:date+'T13:00:00+08:00'});const s={trade_date:date,symbols:{1001:d}};const actual=telegram(s,['1001'],date+'T13:00:00+08:00').filter(x=>x.hit).map(x=>({...x.row,event_type:x.kind==='volume'?'VOLUME_ANOMALY_EVENT':'PRICE_UP_ANOMALY_EVENT',source_event_at:x.row.timestamp}));assert.deepEqual(actual,full.events);assert.equal(full.proof.complete,true);});
await test('deep analysis uses original direction/level/indicator gate and missing plan blocks',()=>{const x=fixture();const a=deepAnalysis({events:[x.proof.event],contexts:{3450:{bars:x.proof.bars,levelInput:x.proof.levelInput}},now:x.proof.now,tradeDate:x.proof.event.trade_date});assert.equal(a.events[0].gate.eligible,false);assert.equal(a.events[0].gate.reason,'PLAN_CONTRACT_MISMATCH');});
await test('valid isolated plan exact gate parity; no real notification port exists',()=>{const x=fixture(),d=x.proof.event.trade_date,rows=[{stock_id:'3450',preopen_action:'LIMIT_UP_LONG',intraday_direction:'long',scenario:'fixture',reasons:[],direction_qualified:true,data_complete:true}];const p={contract:planContract.CONTRACT,trade_date:d,base_date:'2026-09-15',calendar_verified:true,complete:true,status:'complete',mode:'live',source_verified:true,run_id:'OFFLINE_FIXTURE',source_run_id:'OFFLINE_FIXTURE',frozen_at:d+'T08:59:00+08:00',coverage:{twse:1000,tpex:700,total:1700},rules_complete:true,unresolved_rules:[],rows,rows_sha256:planContract.digest(rows)};const a=deepAnalysis({events:[x.proof.event],contexts:{3450:{bars:x.proof.bars,levelInput:x.proof.levelInput}},now:x.proof.now,tradeDate:d,plan:p});assert.equal(a.events[0].gate.eligible,true);assert.deepEqual(require('../../lib/telegram-detectors/level-cross-gate.cjs').verify(a.events,a.evidence),[]);});
await test('dry-run outbox ordering and acknowledgement restart dedup',()=>{const c=client('outbox');c.state.outbox=[{order:1,status:'DRY_RUN_PENDING',delivery_authorized:false},{order:2,status:'DRY_RUN_PENDING',delivery_authorized:false}];c.save(c.state);assert.throws(()=>c.acknowledge(2),/OUTBOX_ORDER/);c.acknowledge(1);const r=client('outbox');r.acknowledge(1);r.acknowledge(2);assert.equal(r.state.outbox.every(x=>x.status==='DRY_RUN_ACKED'),true);});
await test('stale or real-mode gate object rejected before any commit',async()=>{for(const g of [{...gate,as_of:date+'T12:59:00+08:00'},{...gate,mode:'live'}])await assert.rejects(client('stalegate').process(f(1,[]),{gate:g}),/OFFLINE_GATE_CONTEXT/);});
await test('full incremental anomaly -> existing plan/level/cross -> dry outbox replay',async()=>{
 const s='3450',c=client('fulloutbox'),d=data(s);d.current=bars(s,31,'12:29').map((b,i)=>({...b,open:100,high:i===30?101:100,low:100,close:i===30?101:100}));d.levelInput={stock_id:s,trade_date:date,available_at:date+'T08:50:00+08:00',previous_close:100,cost:null,open:null,previous_low:null,gaps:[]};
 const rows=[{stock_id:s,preopen_action:'LIMIT_UP_LONG',intraday_direction:'long',scenario:'isolated fixture',reasons:[],direction_qualified:true,data_complete:true}];
 const plan={contract:planContract.CONTRACT,trade_date:date,base_date:'2026-10-05',calendar_verified:true,complete:true,status:'complete',mode:'live',source_verified:true,run_id:'OFFLINE_FIXTURE',source_run_id:'OFFLINE_FIXTURE',frozen_at:date+'T08:59:00+08:00',coverage:{twse:1000,tpex:700,total:1700},rules_complete:true,unresolved_rules:[],rows,rows_sha256:planContract.digest(rows)};
 const a=f(1,[{kind:'ADMIT',symbol:s}],{plan});await c.process(a,{backfill:()=>({symbol:s,trade_date:date,identity,complete:true,data:d}),gate});assert.equal(c.state.outbox.length,1);assert.equal(c.state.outbox[0].delivery_authorized,false);const r=client('fulloutbox');assert.equal((await r.process(a,{gate})).status,'REPLAY_DEDUP');assert.equal(r.state.outbox.length,1);r.acknowledge(1);assert.equal(client('fulloutbox').state.outbox[0].status,'DRY_RUN_ACKED');
});
await test('0/1/128/129/1024/5000 event frame boundaries, 5001 rejected',async()=>{
 const c=client('boundaries');await c.process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:bf,gate});let seq=2;
 for(const n of [0,1,128,129,1024,5000]){const r=await c.process(f(seq++,Array.from({length:n},()=>({kind:'TRANSPORT',symbol:'1001'}))),{gate});assert.deepEqual(r.discovery,[]);}
 await assert.rejects(c.process(f(seq,Array.from({length:5001},()=>({kind:'TRANSPORT',symbol:'1001'}))),{gate}),/FRAME_CAPACITY/);
});
await test('total row budget and frame byte budget reject without checkpoint',async()=>{
 await assert.rejects(client('totalcap',{totalRows:21}).process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:bf,gate}),/TOTAL_ROWS_CAPACITY/);
 await assert.rejects(client('bytecap',{frameBytes:32}).process(f(1,[]),{gate}),/FRAME_BYTES_CAPACITY/);
});
await test('overlapping async transactions blocked; stale instance reloads committed state',async()=>{
 const a=client('concurrent'),b=client('concurrent');let releaseBackfill;const wait=new Promise(resolve=>releaseBackfill=resolve);
 const first=a.process(f(1,[{kind:'ADMIT',symbol:'1001'}]),{backfill:async s=>{await wait;return bf(s);},gate});
 await assert.rejects(b.process(f(1,[]),{gate}),/CONSUMER_OWNER_BUSY/);releaseBackfill();await first;
 await b.process(f(2,[]),{gate});assert.equal(b.state.seq,2);assert.equal(Object.keys(b.state.symbols).length,1);
});
await test('crashed owner marker not automatically stolen',async()=>{const c=client('ownercrash');fs.writeFileSync(path.join(c.directory,'offline-owner.lock'),'offline crashed fixture');await assert.rejects(c.process(f(1,[]),{gate}),/CONSUMER_OWNER_BUSY/);assert.equal(c.state.seq,0);});
const report={contract:'phase4_offline_tests_v1',status:'PASS',scope:'new isolated consumer; unchanged formula cores; no production runner or sender',count:tests.length,tests,fixture_directory:dir,process_peak_rss_kib:process.resourceUsage().maxRSS,memory:process.memoryUsage(),natural_verified:false,production_connected:false,remaining:['upstream C2/Phase2/3 authenticated durable commit mapping','formal 95/90 verifier integration','real plan/cost/finality availability','real notification exactly-once impossible without downstream idempotency; dry-run only','historical event retraction/re-notification policy remains owner decision']};fs.mkdirSync(path.join(__dirname,'evidence'),{recursive:true});fs.writeFileSync(path.join(__dirname,'evidence/tests.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,count:report.count,dir}));
}
main().catch(e=>{console.error(e.stack);process.exitCode=1;});
