'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {local,read,sha}=require('./producer-handoff.cjs');
function load(file,max=16*1048576){const e=JSON.parse(read(file,max));if(sha(e.payload)!==e.hash)throw Error('HASH');return e.payload;}
function atomic(file,payload,fault){local(file);const tmp=file+'.'+crypto.randomBytes(8).toString('hex')+'.tmp',b=JSON.stringify({payload,hash:sha(payload)});if(Buffer.byteLength(b)>16*1048576)throw Error('LIMIT');const fd=fs.openSync(tmp,'wx');try{fs.writeFileSync(fd,b);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}if(fault==='BEFORE_RENAME')throw Error('CRASH');fs.renameSync(tmp,file);if(fault==='AFTER_RENAME')throw Error('CRASH');return load(file);}
function identity(x){if(!x||!x.owner||!x.host||!x.nonce||!x.epoch||!Number.isSafeInteger(x.pid)||x.pid<1||!Number.isFinite(Date.parse(x.started_at)))throw Error('OWNER_IDENTITY');const b=read(x.authorization?.path||'',1048576);if(sha(b)!==x.authorization?.sha256)throw Error('OWNER_AUTH_HASH');const a=JSON.parse(b);if(a.contract!=='owner-control-authorization-v1'||a.scope!=='ISOLATED_REVIEW'||a.owner!==x.owner||a.host!==x.host||a.epoch!==x.epoch||a.release_sha!==x.release_sha||!/^[a-f0-9]{40}$/.test(x.release_sha||''))throw Error('OWNER_AUTH_BINDING');return sha(x);}
class OwnerControl {
 constructor(dir,owner,probe){this.dir=local(dir);fs.mkdirSync(this.dir,{recursive:true});this.owner=owner;this.id=identity(owner);this.probe=probe;this.file=path.join(dir,'owner.json');}
 acquire(){const fd=fs.openSync(this.file,'wx');try{fs.writeFileSync(fd,JSON.stringify({payload:this.owner,hash:this.id}));fs.fsyncSync(fd);}finally{fs.closeSync(fd);}}
 check(){if(sha(load(this.file))!==this.id)throw Error('OWNER_CHANGED');}
 stop(){this.check();atomic(path.join(this.dir,'stop.json'),{owner:this.id,stop:true});}
 stopped(){this.check();const f=path.join(this.dir,'stop.json');return fs.existsSync(f)&&load(f).owner===this.id;}
 takeover(expected,newOwner){this.check();if(expected!==this.id||identity(newOwner)===this.id)throw Error('TAKEOVER_IDENTITY');const result=this.probe(this.owner);if(result?.status!== 'CONFIRMED_DEAD_EXACT_IDENTITY'||result.identity_hash!==this.id||!result.evidence_ref)throw Error('OWNER_NOT_PROVEN_DEAD');const fence=path.join(this.dir,'takeover.lock'),fd=fs.openSync(fence,'wx');try{this.check();const archive=this.file+'.'+this.id+'.retired';fs.renameSync(this.file,archive);const next=new OwnerControl(this.dir,newOwner,this.probe);next.acquire();return next;}finally{fs.closeSync(fd);fs.unlinkSync(fence);}}
}
class CataloguePublisher {
 constructor(dir,control){this.dir=local(dir);fs.mkdirSync(dir,{recursive:true});this.control=control;this.file=path.join(dir,'catalogue-state.json');}
 publish(...args){this.control.check();const lock=path.join(this.dir,'publish.lock'),fd=fs.openSync(lock,'wx');try{return this._publish(...args);}finally{fs.closeSync(fd);fs.unlinkSync(lock);}}
 _publish(catalogue,proofs,{retainedThrough=0,fault,reader,retention}={}){this.control.check();if(this.control.stopped())throw Error('STOP');const old=fs.existsSync(this.file)?load(this.file):null;const c={...catalogue};delete c.hash;if(sha(c)!==catalogue.hash||catalogue.gap||catalogue.continuity!=='CONTIGUOUS_FROM_HANDOFF'||catalogue.epoch!==this.control.owner.epoch||catalogue.segments.length>256||proofs.length>800)throw Error('CATALOGUE');if(old&&(old.catalogue.binding!==catalogue.binding||catalogue.published_through<old.catalogue.published_through))throw Error('REGRESSION');let seq=catalogue.anchor?.sequence||0;if(seq>retainedThrough)throw Error('UNACKED_RETENTION');if(seq>0){if(!retention)throw Error('RETENTION_PROOF_REQUIRED');const r=JSON.parse(read(retention.root_file,4*1048576)),fb=read(retention.frame_file,8*1048576),f=JSON.parse(fb),cur=f.dual?.cursors?.[retention.kind];if(sha(JSON.stringify(r.payload))!==r.sha256||sha(fb)!==r.payload.sourceCursor.intent_hash||f.dual.binding[retention.kind]!==catalogue.binding||!cur||cur.sequence<seq||cur.sequence!==retainedThrough||cur.sequence===seq&&cur.commit_hash!==catalogue.anchor.commit_hash)throw Error('RETENTION_READBACK');}for(const s of catalogue.segments){if(s.first!==seq+1||s.last<s.first)throw Error('GAP');seq=s.last;}if(seq!==catalogue.published_through)throw Error('GAP');if(!reader||reader.identity.binding!==catalogue.binding)throw Error('READER_BINDING');let cursor=old?.cursor||{...reader.identity.cursor,kind:reader.identity.kind,trade_date:reader.identity.trade_date,epoch:reader.identity.epoch,binding:reader.identity.binding};const checked=[];
if(cursor.sequence<catalogue.published_through){const tmp=path.join(this.dir,'validate-'+crypto.randomBytes(8).toString('hex')+'.json');fs.writeFileSync(tmp,JSON.stringify(catalogue),{flag:'wx'});try{let n=0,total=0;while(cursor.sequence<catalogue.published_through){if(++n>16)throw Error('PUBLICATION_BACKPRESSURE');const view=Object.create(reader);view.cursor=()=>cursor;const page=view.poll(tmp);if(page.status!=='PAGE')throw Error('INCOMPLETE_PUBLICATION');total+=page.page.bytes;if(total>64*1048576)throw Error('PUBLICATION_BACKPRESSURE');checked.push(...page.page.proofs);cursor=page.page.next;}}finally{fs.unlinkSync(tmp);}}
const required=new Map([...(old?.proofs||[]),...checked].filter(p=>catalogue.segments.some(s=>path.dirname(p.file)===s.dir)).map(p=>[p.file,p.sha256]));if(required.size!==new Map(proofs.map(p=>[p.file,p.sha256])).size||proofs.some(p=>required.get(p.file)!==p.sha256))throw Error('PROOF_SET');let bytes=0;for(const p of proofs){const b=read(p.file,8*1048576);bytes+=b.length;if(bytes>64*1048576||sha(b)!==p.sha256)throw Error('SEGMENT_HASH');}if(old)for(const p of old.proofs){const same=proofs.find(x=>x.file===p.file);if(same&&same.sha256!==p.sha256)throw Error('IMMUTABLE_SEGMENT');}return atomic(this.file,{catalogue,proofs,cursor,owner:this.control.id,previous:old?sha(old):null,retainedThrough},fault);}
 read(){const x=load(this.file);for(const p of x.proofs)if(sha(read(p.file,8*1048576))!==p.sha256)throw Error('SEGMENT_HASH');return x;}
}
module.exports={load,atomic,OwnerControl,CataloguePublisher};
