'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict');
const {Wiring,flags}=require('./wiring.cjs'),{hash,bytes,OfflineStore}=require('../integration/offline-store.cjs');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'mp-release-wiring-')),tests=[];
const frame={epoch:'OFFLINE',trade_date:'2026-10-08',sequence:1},env={MP_PHASE2_ENABLED:'1',MP_PHASE3_ENABLED:'1',MP_PHASE4_ENABLED:'1'};
function ports(dir,operations=[x=>x,x=>x,x=>x]){return operations.map((operation,i)=>({scope:'ISOLATED',version:'ISOLATED_TEST_V1',prepare:async(value,ctx)=>{const f=path.join(dir,ctx.idempotency_key+'-'+i+'.json');if(fs.existsSync(f))return JSON.parse(fs.readFileSync(f)).payload;const payload=await operation(value,ctx);fs.writeFileSync(f,JSON.stringify({...ctx.input,idempotency_key:ctx.idempotency_key,payload,sha256:hash(bytes(payload))}),{flag:'wx'});return payload;},readback:async ctx=>JSON.parse(fs.readFileSync(path.join(dir,ctx.idempotency_key+'-'+i+'.json')))}));}
(async()=>{
 const off=path.join(root,'off');assert.equal((await new Wiring({directory:off}).run(frame)).status,'OFF');assert(!fs.existsSync(off));tests.push('default OFF no filesystem/ports');
 for(const e of [{MP_PHASE3_ENABLED:'1'},{MP_PHASE4_ENABLED:'1'},{MP_PHASE2_ENABLED:'true'}])assert.throws(()=>flags(e));tests.push('dependency and strict flags');
 assert.throws(()=>new Wiring({directory:root,mode:'PRODUCTION'}),/NOT_AUTHORIZED/);tests.push('formal mode refused');
 for(const count of [1,2,3]){const d=fs.mkdtempSync(path.join(root,'p-')),e=Object.fromEntries(Object.keys(env).slice(0,count).map(k=>[k,'1'])),w=new Wiring({directory:path.join(d,'root'),env:e,ports:ports(d)}),r=await w.run(frame);assert.deepEqual(r.called,[2,3,4].slice(0,count));assert.equal((await w.run(frame)).status,'REPLAY_DEDUP');await assert.rejects(w.run({...frame,x:1}),/REPLAY_CONFLICT/);tests.push('phases through '+(count+1)+' independent and dedup');}
 const d=fs.mkdtempSync(path.join(root,'stop-'));let stopped=false;const ps=ports(d,[x=>{stopped=true;return x},x=>x,x=>x]);assert.equal((await new Wiring({directory:path.join(d,'root'),env,ports:ps,stop:()=>stopped}).run(frame)).status,'STOPPED');assert(!fs.existsSync(path.join(d,'root/root.json')));tests.push('STOP between phases retains staged data no root');
 const q=fs.mkdtempSync(path.join(root,'bad-')),p=ports(q),normal=p[1].readback;p[1].readback=async ctx=>({...await normal(ctx),sequence:99});const w=new Wiring({directory:path.join(q,'root'),env,ports:p});await assert.rejects(w.run(frame),/READBACK/);assert(!fs.existsSync(path.join(q,'root/root.json')));p[1].readback=normal;assert.equal((await w.run(frame)).status,'OFFLINE_READBACK_VERIFIED');assert.equal(fs.readdirSync(q).filter(x=>x.endsWith('.json')).length,3);tests.push('failed readback resumes staged idempotent ports');
 await assert.rejects(w.run({...frame,sequence:3}),/SEQUENCE_GAP/);await assert.rejects(w.run({...frame,sequence:2,epoch:'other'}),/REBASE/);await assert.rejects(new Wiring({directory:path.join(q,'root'),env:{MP_PHASE2_ENABLED:'1'},ports:p}).run({...frame,sequence:2}),/FLAG_REBASE/);tests.push('sequence identity and flag drift blocked');
 // Real Phase 2 -> 3 -> 4 calculations; only the boundary I/O is an offline port.
 const chain=fs.mkdtempSync(path.join(root,'e2e-')),date=frame.trade_date,asOf=date+'T13:00:00+08:00';
 const {CandleLifecycle}=require('../phase2/candle-lifecycle.cjs'),{derive}=require('../phase3/candle-derived.cjs'),{IncrementalDiscovery}=require('../phase3/incremental-discovery.cjs'),{createOracle}=require('../phase3/original-oracle.cjs'),{fixture,quote}=require('../phase3/fixture.cjs'),{bind}=require('../integration/routing-contract.cjs'),fx=require('../phase4/fixtures.cjs'),{evaluate}=require('../integration/evaluate-routed.cjs');
 const binding=bind({trade_date:date,epoch:frame.epoch,activeSymbols:['1000','1001'],prioritySymbols:[],sourceAnchors:{fixture:{epoch:frame.epoch,trade_date:date,sequence:0,commit_hash:'OFFLINE'}}});
 const real=ports(chain,[()=>{const life=new CandleLifecycle({directory:path.join(chain,'p2'),tradeDate:date,epoch:frame.epoch});return life.apply({sequence:1,nowMs:Date.parse(asOf),rows:[{symbol:'1000',market:'TSE',tradeDate:date,candleTime:date+'T12:59:00+08:00',candleSeenAt:asOf,source:'fugle-ws-candles',sourceChannel:'candles',candleOrigin:'websocket_candle',restRepairRow:false,intradayOddLot:false,synthetic:false,volumeStrategyUsable:true,open:105,high:107,low:104,close:106,volume:100}]});},events=>{assert.equal(events.length,1);const snap=fixture(2);snap.epoch=frame.epoch;const engine=new IncrementalDiscovery({oracle:createOracle()});engine.baseline(snap);return {events,discovery:engine.process({epoch:frame.epoch,tradeDate:date,sequence:1,continuity:'CONTIGUOUS',asOf,events:[{resource:'intradayMap',symbol:'1000',value:derive(events.map(x=>x.payload),date,asOf)[0][1]},{resource:'quoteMap',symbol:'1000',value:quote('1000',106,20000,asOf)}]})};},async packet=>{const store=new OfflineStore(path.join(chain,'p4')),discovery=packet.discovery;const backfill=async s=>{const data=fx.data(s,{date});for(const e of packet.events.filter(e=>e.symbol===s||e.payload.symbol===s)){const r=e.payload;const b={stock_id:s,trade_date:date,timestamp:r.candle_time,open:r.open,high:r.high,low:r.low,close:r.close,volume_raw:r.volume,volume_raw_unit:r.payload.volume_unit.toUpperCase(),complete:true,is_synthetic:r.synthetic,volume_strategy_usable:r.volume_strategy_usable,source:r.source,available_at:r.updated_at};data.current=data.current.filter(x=>Date.parse(x.timestamp)!==Date.parse(b.timestamp));data.current.push(b);data.current.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));}return {symbol:s,trade_date:date,verified:true,data};};await evaluate({store,binding,input:{discovery,changedSymbols:['1000'],candleSymbols:['1000'],asOf},changes:{},gate:fx.gate(binding.sha256,{date,asOf}),backfill,sequence:1,sourceCursor:{status:'OFFLINE_FIXED_SEGMENT',epoch:frame.epoch}});return store.root();}]);
 const c=new Wiring({directory:path.join(chain,'control'),env,ports:real});assert.equal((await c.run(frame)).status,'OFFLINE_READBACK_VERIFIED');assert.equal((await c.run(frame)).status,'REPLAY_DEDUP');assert(new OfflineStore(path.join(chain,'p4')).root().telegram['1000']);assert.equal((await new Wiring({directory:path.join(chain,'control'),env,ports:real}).run(frame)).status,'REPLAY_DEDUP');tests.push('real phase2 -> phase3 -> phase4 offline readback E2E and restart dedup');
 console.log(JSON.stringify({status:'PASS',tests,root,formal_connected:false,notifications:0}));
})().catch(e=>{console.error(e);process.exitCode=1});


